export const ADD_NEW_CLIENT_SUCCESS = 'ADD_NEW_CLIENT_SUCCESS';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const CLIENT_WAS_UPDATED = 'CLIENT_WAS_UPDATED';

export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const CLIENTS_FETCH_DATA_SUCCESS = 'CLIENTS_FETCH_DATA_SUCCESS';

export const GET_ALL_PICTURES = 'GET_ALL_PICTURES';
export const ADD_NEW_PICTURE = 'ADD_NEW_PICTURE';
export const UPDATE_PICTURE = 'UPDATE_PICTURE';
export const DELETE_PICTURE = 'DELETE_PICTURE';

export const COMBINE_ALL = 'COMBINE_ALL';

export const PICTURES_FETCH_DATA_SUCCESS = 'PICTURES_FETCH_DATA_SUCCESS';

export const OPEN_OR_CLOSE_COMPONENT = 'OPEN_OR_CLOSE_COMPONENT';



